### ISSUE TITLE
practica de realidad aumentada 3d

### ISSUE THREAD

**Issue by Litzy-12** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-obed#2]
[PracticaUbiGPS_Obed_Litzy.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-obed/files/6645516/PracticaUbiGPS_Obed_Litzy.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20 %

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
